#spring.application.name="P2B WEB Backend"
gemini.api.url=${YOUR_API_URL}
gemini.api.key=${YOUR_API_KEY}
server.port=8080
groq.api.key=

# PostgreSQL Config
spring.datasource.url=jdbc:postgresql://localhost:5432/p2b_db
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate settings (Auto-table creation)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# MongoDB Configuration and (Chat logs)
spring.data.mongodb.uri=mongodb://localhost:27017/p2b_db



# Google Auth Config (ACTUAL CLIENT ID)
google.client.id=






